# Generated by Django 5.0.3 on 2024-03-13 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_room_host_room_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mp3', 'wav'])]),
        ),
    ]
