# Generated by Django 5.0.3 on 2024-03-13 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_room_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='description',
            new_name='comment',
        ),
        migrations.RemoveField(
            model_name='room',
            name='file',
        ),
    ]
