# Generated by Django 5.0.3 on 2024-03-13 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_room_country_alter_room_name_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='country',
            field=models.CharField(choices=[('USA', 'United States'), ('CAN', 'Canada'), ('UK', 'United Kingdom')], default='', max_length=50),
        ),
    ]
