# Generated by Django 5.0.3 on 2024-03-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_room_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='country',
            field=models.CharField(choices=[('NL', 'Netherlands'), ('BE', 'Belgium'), ('DE', 'Germany'), ('FR', 'France'), ('UK', 'United Kingdom')], default='Choose a country', max_length=50),
        ),
    ]
