# Generated by Django 5.0.3 on 2024-03-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_room_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='country',
            field=models.CharField(blank=True, choices=[('', 'Choose a country'), ('NL', 'Netherlands'), ('BE', 'Belgium'), ('DE', 'Germany'), ('FR', 'France'), ('UK', 'United Kingdom')], default='', max_length=50),
        ),
    ]
